name: medical_diagnostic_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.11.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase packages
  supabase_flutter: ^2.12.4
  
  # Image picking
  image_picker: ^1.0.0
  
  # State management
  provider: ^6.0.0
  
  # Others
  intl: ^0.20.2
  http: ^1.1.0
  path: ^1.9.0
  
  # TO read the pixels of the image
  image: ^4.1.3
  font_awesome_flutter: ^11.0.0
  material_symbols_icons: ^4.2928.1
  figma_squircle: ^0.6.3
  dotted_border: ^3.1.0
  skeletonizer: ^2.1.3
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  permission_handler: ^11.3.1
  wechat_assets_picker: ^9.0.0
  pinput: ^5.0.1
  sms_autofill: ^2.4.1
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.0
  google_fonts: ^6.3.0
  carousel_slider: ^5.1.1
  
  #google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
     - assets/images/onboarding1.png
     - assets/images/onboarding2.png
     - assets/images/onboarding3.png
     - assets/images/search.png
     - assets/images/image_without_text.png
     - assets/images/lab_image_without_text.png
     - assets/images/testified_banner_cbc_2.png
     - assets/images/fullbody_checkup_banner1.jpeg
     - assets/images/diabetes_screening_banner.jpeg
     - assets/images/quick_reports_banner.jpeg
     - assets/images/join_healthplus_banner.jpeg
     - assets/images/lab_tests_at_home_image.png
     - assets/images/book_tests_at_partner_labs_image.png
     - assets/images/prescription_icon.png
    



