name: medical_diagnostic_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: "3.11.5"

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase packages
  supabase_flutter: ^2.12.4
  
  # Image picking
  image_picker: ^1.0.0
  
  # State management
  provider: ^6.0.0
  
  # Others
  intl: ^0.20.2
  http: ^1.1.0
  path: ^1.9.0
  
  # TO read the pixels of the image
  image: ^4.1.3
  font_awesome_flutter: ^11.0.0
  material_symbols_icons: ^4.2928.1
  figma_squircle: ^0.6.3
  #google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/TestifiedLogo(NEW).png



