name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      
      - uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: "3.41.9" # or any version >= 3.11.1
          channel : 'stable'
          cache : true # Optional: speeds up your builds

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test
